food = input("Name of the food: ")
plant = input("Name of the plant: ")
methodofcooing = input("Name of the method of cooking: ")
burnedfood = input("What word describes burned food: ")
DIYitem = input("Name of the DIY item: ")
print("Menu")
print(methodofcooing,food,"with",burnedfood,plant,"on a bed of",DIYitem)